# Generated by Django 4.1.2 on 2022-11-29 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 17, 20, 59, 579447, tzinfo=datetime.timezone.utc)),
        ),
    ]
