# Generated by Django 4.1.2 on 2022-12-06 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 14, 47, 18, 882322, tzinfo=datetime.timezone.utc)),
        ),
    ]
